services:
  app:
    build: .
    image: devops-portfolio:local
    container_name: app
    environment:
      - PORT=8000
    labels:
      - "logging=promtail"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx-http.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    labels:
      - "logging=promtail"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    labels:
      - "logging=promtail"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=pishchik-dev.tech
      - GF_SERVER_ROOT_URL=http://pishchik-dev.tech:3001/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
      - loki
    labels:
      - "logging=promtail"
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./infra/logging/loki/loki-config.yml:/etc/loki/config.yml:ro
    ports:
      - "3100:3100"
    labels:
      - "logging=promtail"
  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/logging/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    depends_on:
      - loki

volumes:
  grafana-data:
