services:
  app:
    build: .
    image: devops-portfolio:local
    container_name: app
    environment:
      - PORT=8000
    labels:
      - "logging=promtail"
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    ports:
      - "3000:3000"
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./infra/logging/loki/loki-config.yml:/etc/loki/config.yml:ro
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/logging/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    depends_on:
      - loki

volumes:
  grafana-data:
