services:
  app:
    build: .
    image: devops-portfolio:local
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/backups:/opt/backups
      - ./infra/backup/backup.sh:/opt/devops-portfolio/infra/backup/backup.sh:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "logging=promtail"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./infra/nginx/webroot:/var/www/certbot:ro
    depends_on:
      - app
      - grafana
      - prometheus
      - loki
    labels:
      - "logging=promtail"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./infra/nginx/webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@pishchik-dev.tech --agree-tos --no-eff-email -d pishchik-dev.tech -d www.pishchik-dev.tech

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
      - "--web.listen-address=0.0.0.0:9090"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/monitoring/prometheus/rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
    labels:
      - "logging=promtail"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.listen-address=0.0.0.0:9093"
      - "--log.level=debug"
    volumes:
      - ./infra/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-your_bot_token_here}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-your_chat_id_here}
    env_file:
      - .env
    labels:
      - "logging=promtail"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9100:9100"
    labels:
      - "logging=promtail"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://pishchik-dev.tech/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./infra/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./infra/monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards.yml:ro
      - ./infra/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    labels:
      - "logging=promtail"

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/loki-config.yml"]
    volumes:
      - ./infra/logging/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
    ports:
      - "3100:3100"
    labels:
      - "logging=promtail"

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    user: root
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./infra/logging/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    depends_on:
      - loki
    labels:
      - "logging=promtail"

volumes:
  grafana-data: