- hosts: web
  become: yes
  tasks:
    - name: 
      apt:
        update_cache: yes
        upgrade: dist

    - name:  Docker  Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: 
      file:
        path: ~/MySite
        state: directory
