server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Обязательные лейблы для Loki
      - source_labels: ['__meta_docker_container_name']
        target_label: container_name
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - target_label: job
        replacement: 'docker'
      # Добавляем фиксированный лейбл для всех контейнеров
      - target_label: level
        replacement: 'info'
      # Фильтруем только работающие контейнеры
      - source_labels: ['__meta_docker_container_state']
        regex: running
        action: keep
