{
 "title": "Ansible Galaxy role overview",
 "description": "High level overview of an Ansible Galaxy role's statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "version",
    "label": "version",
    "query": "ansible_galaxy_role_version_info"
   },
   { "name": "maintainer", "label": "Maintainer", "query": "ansible_galaxy_role_downloads" },
   {
    "name": "project",
    "label": "Project",
    "query": "ansible_galaxy_role_downloads{maintainer=\"$maintainer\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Role",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "ansible_galaxy_role_version_info{maintainer=\"$maintainer\",project=\"$project\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "ansible_galaxy_role_version_info{maintainer=\"$maintainer\",project=\"$project\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Version Age",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - ansible_galaxy_role_imported{maintainer=\"$maintainer\",project=\"$project\"}) * 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Downloads 24h",
   "type": "singlestat",
   "description": "Requires at least 24h of data to count",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"} - ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"} offset 1d"
    }
   ]
  },
  {
   "title": "Downloads 7d",
   "type": "singlestat",
   "description": "Requires at least 7d of data to count",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"} - ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"} offset 7d"
    }
   ]
  },
  {
   "title": "Galaxy community surveys",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_community_surveys{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Galaxy community score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_community_score{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Github forks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_forks{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Github stars",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_stars{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Galaxy watchers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_watchers{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Github open issues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_open_issues{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Total versions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ansible_galaxy_role_versions{maintainer=\"$maintainer\",project=\"$project\"}"
    }
   ]
  },
  {
   "title": "Created",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - ansible_galaxy_role_created{maintainer=\"$maintainer\",project=\"$project\"}) * 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Downloads (15m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(delta(ansible_galaxy_role_downloads{maintainer=\"$maintainer\",project=\"$project\"}[15m]))",
     "legendFormat": "downloads"
    }
   ]
  }
 ]
}