{
 "title": "Ansible Shed (ansible-playbook)",
 "description": "Ansible run statistics parsed out of ansible-playbook",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ansible-playbook UNIX returncode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_last_run_returncode" }
   ]
  },
  {
   "title": "ansible-playbook Runtime (Minutes)",
   "type": "timeseries",
   "description": "How long did the ansible run take?",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_last_run_time / 60" }
   ]
  },
  {
   "title": "Last Update (UNIX Timestamp)",
   "type": "timeseries",
   "description": "When did we last update stats",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_stats_last_updated" }
   ]
  },
  {
   "title": "ok",
   "type": "timeseries",
   "description": "How long did the ansible run take?",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_ok" }
   ]
  },
  {
   "title": "failed",
   "type": "timeseries",
   "description": "How long did the ansible run take?",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_failed" }
   ]
  },
  {
   "title": "unrechable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_unreachable" }
   ]
  },
  {
   "title": "changed",
   "type": "timeseries",
   "description": "How long did the ansible run take?",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_changed" }
   ]
  },
  {
   "title": "skipped",
   "type": "timeseries",
   "description": "How long did the ansible run take?",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_skipped" }
   ]
  },
  {
   "title": "rescued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_rescued" }
   ]
  },
  {
   "title": "ignored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ansible_ignored" }
   ]
  }
 ]
}