name: ci-cd

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  infra:
    if: ${{ secrets.APPLY_INFRA == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.tf-output.outputs.public_ip }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Terraform Init/Apply (YC)
        working-directory: infra/terraform
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_yc_zone: ${{ secrets.YC_ZONE }}
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_public_ssh_key: ${{ secrets.PUBLIC_SSH_KEY }}
          TF_VAR_ubuntu_image_id: ${{ secrets.UBUNTU_IMAGE_ID }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false
      - name: Capture Terraform outputs
        id: tf-output
        working-directory: infra/terraform
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          file: Dockerfile

  deploy:
    needs: [build-and-push, infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible and collections
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-core
          mkdir -p ~/.ansible/collections
          ansible-galaxy collection install community.docker --force
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add host key to known_hosts
        run: |
          if [ -z "${{ needs.infra.outputs.public_ip }}" ]; then echo "::error::Terraform did not output public_ip. Ensure APPLY_INFRA=true and YC_* secrets set"; exit 1; fi
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ needs.infra.outputs.public_ip }}" -p 22 >> ~/.ssh/known_hosts
      - name: Update inventory with VM IP
        run: |
          sed -i "s/YOUR_VM_IP/${{ needs.infra.outputs.public_ip }}/" infra/ansible/inventory.ini
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i infra/ansible/inventory.ini infra/ansible/site.yml

