name: ci-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/devops-portfolio:latest
          file: Dockerfile

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible and collections
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-core
          mkdir -p ~/.ansible/collections
          ansible-galaxy collection install community.docker --force
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Update inventory with VM IP
        run: |
          sed -i "s/YOUR_VM_IP/${{ secrets.VM_PUBLIC_IP }}/" infra/ansible/inventory.ini
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i infra/ansible/inventory.ini infra/ansible/site.yml

