name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
          yc --version

      - name: Configure Yandex Cloud
        run: |
          yc config set token ${{ secrets.YC_OAUTH_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc config set compute-default-zone ${{ secrets.YC_ZONE }}

      - name: Terraform init & apply
        working-directory: infra/terraform
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Get external IP
        id: ip
        working-directory: infra/terraform
        run: |
          echo "EXTERNAL_IP=$(terraform output -raw external_ip)" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EXTERNAL_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "MySite" ]; then
              git clone https://github.com/${{ github.repository }} MySite
            fi
            cd MySite
            git pull origin main
            docker-compose down
            docker-compose up -d --build
